openapi: 3.0.0
info:
  title: Pharmacy Service API
  version: 1.0.2
  description: API documentation for the Pharmacy Service, focusing on managing authentication.
servers:
  - url: https://pharmacyservice-a6acf2bebehsgcfc.canadacentral-01.azurewebsites.net/api/v1
    description: Development server

paths:
  /auth/register:
    post:
      summary: Register a new pharmacy
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  example: pharmacy@example.com
                password:
                  type: string
                  format: password
                  example: secure_password
                name:
                  type: string
                  example: Pharmacy ABC
      responses:
        '201':
          description: Pharmacy registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Pharmacy registered successfully
                  role:
                    type: string
                    example: pharmacy
        '400':
          description: Pharmacy already exists
        '500':
          description: Error registering pharmacy

  /auth/login:
    post:
      summary: Login a pharmacy
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: pharmacy@example.com
                password:
                  type: string
                  format: password
                  example: secure_password
      responses:
        '200':
          description: Pharmacy logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  role:
                    type: string
                    example: pharmacy
                  name:
                    type: string
                    example: Pharmacy ABC
        '404':
          description: Pharmacy not found
        '401':
          description: Invalid credentials
        '500':
          description: Error logging in

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
